[[data]]
"Sl no" = 1
"Name of the prabandham" = 'Periazhvar Thirumozhi'
"Starting from" = 1
"Ending with" = 473
"Number of pasurams" = 473
"Sung by" = 'Periyalvar'

[[data]]
"Sl no" = 2
"Name of the prabandham" = 'Thiruppavai'
"Starting from" = 474
"Ending with" = 503
"Number of pasurams" = 30
"Sung by" = 'Aandaal'

[[data]]
"Sl no" = 3
"Name of the prabandham" = 'Nachiar Tirumozhi'
"Starting from" = 504
"Ending with" = 646
"Number of pasurams" = 143
"Sung by" = 'Aandaal'

[[data]]
"Sl no" = 4
"Name of the prabandham" = 'Perumal Thirumozhi'
"Starting from" = 647
"Ending with" = 751
"Number of pasurams" = 105
"Sung by" = 'Kulasekara alvar'

[[data]]
"Sl no" = 5
"Name of the prabandham" = 'Thiruchchanda Viruththam'
"Starting from" = 752
"Ending with" = 871
"Number of pasurams" = 120
"Sung by" = 'Thirumalisai alvar'

[[data]]
"Sl no" = 6
"Name of the prabandham" = 'Thirumalai'
"Starting from" = 872
"Ending with" = 916
"Number of pasurams" = 45
"Sung by" = 'Thondaradippodi alvar'

[[data]]
"Sl no" = 7
"Name of the prabandham" = 'Thiruppalliyezhuchchi'
"Starting from" = 917
"Ending with" = 926
"Number of pasurams" = 10
"Sung by" = 'Thondaradippodi alvar'

[[data]]
"Sl no" = 8
"Name of the prabandham" = 'Amalanadhi piran'
"Starting from" = 927
"Ending with" = 936
"Number of pasurams" = 10
"Sung by" = 'Thiruppaan alvar'

[[data]]
"Sl no" = 9
"Name of the prabandham" = 'Kanni Nun Siruththambu'
"Starting from" = 937
"Ending with" = 947
"Number of pasurams" = 11
"Sung by" = 'Madhurakavi Alvar'

[[data]]
"Sl no" = 10
"Name of the prabandham" = 'Peria Thirumozhi'
"Starting from" = 948
"Ending with" = 2031
"Number of pasurams" = 1084
"Sung by" = 'Thirumangai alvar'

[[data]]
"Sl no" = 11
"Name of the prabandham" = 'Kurun Thandagam'
"Starting from" = 2032
"Ending with" = 2051
"Number of pasurams" = 20
"Sung by" = 'Thirumangai alvar'

[[data]]
"Sl no" = 12
"Name of the prabandham" = 'Nedum Thandagam'
"Starting from" = 2052
"Ending with" = 2081
"Number of pasurams" = 30
"Sung by" = 'Thirumangai alvar'

[[data]]
"Sl no" = 13
"Name of the prabandham" = 'Mudhal Thiruvandhadhi'
"Starting from" = 2082
"Ending with" = 2181
"Number of pasurams" = 100
"Sung by" = 'Poigai Alvar'

[[data]]
"Sl no" = 14
"Name of the prabandham" = 'Irandam Thiruvandhadhi'
"Starting from" = 2182
"Ending with" = 2281
"Number of pasurams" = 100
"Sung by" = 'Bhoothathalvar'

[[data]]
"Sl no" = 15
"Name of the prabandham" = 'Moonram Thiruvandhadhi'
"Starting from" = 2282
"Ending with" = 2381
"Number of pasurams" = 100
"Sung by" = 'Peyalvar'

[[data]]
"Sl no" = 16
"Name of the prabandham" = 'Naanmugan Thiruvandhadhi'
"Starting from" = 2382
"Ending with" = 2477
"Number of pasurams" = 96
"Sung by" = 'Thirumalisai alvar'

[[data]]
"Sl no" = 17
"Name of the prabandham" = 'Thiruviruththam'
"Starting from" = 2478
"Ending with" = 2577
"Number of pasurams" = 100
"Sung by" = 'Nammalvar'

[[data]]
"Sl no" = 18
"Name of the prabandham" = 'Thiruvasiriyam'
"Starting from" = 2578
"Ending with" = 2584
"Number of pasurams" = 7
"Sung by" = 'Nammalvar'

[[data]]
"Sl no" = 19
"Name of the prabandham" = 'Peria Thiruvandhadhi'
"Starting from" = 2585
"Ending with" = 2671
"Number of pasurams" = 87
"Sung by" = 'Nammalvar'

[[data]]
"Sl no" = 20
"Name of the prabandham" = 'Thiruvezhukkurrirukkai'
"Starting from" = 2672
"Ending with" = 2672
"Number of pasurams" = 1
"Sung by" = 'Thirumangai alvar'

[[data]]
"Sl no" = 21
"Name of the prabandham" = 'Siriya Thirumadal'
"Starting from" = 2673
"Ending with" = 2712
"Number of pasurams" = 40
"Sung by" = 'Thirumangai alvar'

[[data]]
"Sl no" = 22
"Name of the prabandham" = 'Peria Thirumadal'
"Starting from" = 2713
"Ending with" = 2790
"Number of pasurams" = 78
"Sung by" = 'Thirumangai alvar'

[[data]]
"Sl no" = 23
"Name of the prabandham" = 'Thiruvay Mozhi'
"Starting from" = 2791
"Ending with" = 3892
"Number of pasurams" = 1102
"Sung by" = 'Nammalvar'

[[data]]
"Sl no" = 24
"Name of the prabandham" = 'Ramanuja Nootrandhadi'
"Starting from" = 3893
"Ending with" = 4000
"Number of pasurams" = 108
"Sung by" = 'Thiruvarangathu Amudhanaar'
